from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
from crewai import Agent, Task, Crew, LLM
from dotenv import load_dotenv
import json
import re

load_dotenv()

app = FastAPI()

# ----- LLM -----
llm = LLM(
    model="groq/llama-3.1-8b-instant",
    temperature=0,  # deterministic JSON output
)

# ----- Agent -----
analyst = Agent(
    role="Software Quality Assurance Principal Engineer",
    goal="Generate structured, production-grade API test cases in strict JSON format.",
    backstory="Senior QA architect specializing in API validation, edge case design, and contract-based testing.",
    llm=llm,
    verbose=False
)

# ----- Request Model -----
class AnalysisRequest(BaseModel):
    topic: str


def extract_json(raw_text: str):
    """
    Safely extract and parse JSON array from LLM response.
    """

    # Remove markdown fences if model adds them
    raw_text = re.sub(r"```json|```", "", raw_text).strip()

    # Extract JSON array only
    match = re.search(r"\[.*\]", raw_text, re.DOTALL)
    if not match:
        raise ValueError("No JSON array found in LLM response.")

    json_str = match.group(0)

    # Remove illegal control characters
    json_str = re.sub(r'[\x00-\x1F\x7F]', '', json_str)

    return json.loads(json_str)


@app.post("/analyze")
def analyze(request: AnalysisRequest):

    task = Task(
        description=f"""
        Generate comprehensive API test cases for the following topic:

        Topic: {request.topic}

        Requirements:
        - Return ONLY valid JSON.
        - No explanations.
        - No markdown.
        - Output must be a JSON array.
        - Do NOT generate curl commands.
        - Represent request as structured object:
            {{
              "method": "...",
              "endpoint": "...",
              "headers": {{ }},
              "body": {{ }}
            }}
        """,
        expected_output="""
        [
          {
            "testCaseId": "TC001",
            "description": "...",
            "input": {
              "request": {
                "method": "POST",
                "endpoint": "/api/example",
                "headers": {},
                "body": {}
              }
            },
            "expectedOutput": {
              "statusCode": 200,
              "response": "..."
            }
          }
        ]
        """,
        agent=analyst
    )

    crew = Crew(
        agents=[analyst],
        tasks=[task]
    )

    result = crew.kickoff(inputs={"topic": request.topic})
    raw_text = result.raw  # <-- important
    try:
        parsed = extract_json(raw_text)
    except Exception as e:
        raise HTTPException(
            status_code=500,
            detail=f"Invalid JSON generated by LLM: {str(e)}"
        )

    return {
        "status": "success",
        "count": len(parsed),
        "result": parsed
    }
